inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - node_modules/**/*

# Ruby
Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Style/RegexpLiteral:
  AllowInnerSlashes: true

# Rspec
RSpec/ExampleLength:
  Enabled: false
