inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - node_modules/**/*

# Ruby
Metrics/MethodLength:
  Exclude:
    - bin/bundle
    - db/migrate/*

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Style/Documentation:
  Exclude:
    - spec/**/*
    - app/models/*
    - app/controllers/*
    - app/mailers/*
    - app/helpers/*
    - config/application.rb
    - db/migrate/*

Style/RegexpLiteral:
  AllowInnerSlashes: true

# Rspec
RSpec/ExampleLength:
  Enabled: false
