inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - node_modules/**/*

# Ruby
Metrics/MethodLength:
  Exclude:
    - bin/bundle
    - db/migrate/*

Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - spec/**/*.rb

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Style/Documentation:
  Exclude:
    - config/application.rb
    - spec/**/*
    - app/models/**/*.rb
    - app/controllers/**/*.rb
    - app/mailers/**/*.rb
    - app/helpers/**/*.rb
    - db/migrate/**/*.rb

Style/ClassAndModuleChildren:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/SymbolArray:
  EnforcedStyle: percent

# Rspec
RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

