language: ruby
rvm: 2.7
cache:
  - bundler
  - yarn

services: postgresql

before_install:
  - nvm install node && nvm use node

install:
  - yarn --frozen-lockfile
  - bundle install --path=vendor/bundle --jobs=3 --retry=3

before_script:
  - RAILS_ENV=test bundle exec rails webpacker:compile
  - psql -c 'create database instavideo_test;' -U postgres

script:
  - bundle exec rubocop
  - bundle exec brakeman -6 -q
  - bundle exec rspec
  - git fetch origin master:master
  - bundle exec undercover -c master
